### PR TITLE
Fix `\o` crasher and allow `(?)`

### LINKED ISSUE #472: `\o` crashes the parser
`/\o/` hits a fatal error in the parser

### PR DESCRIPTION
**Pull request by hamishknight**
Separate these changes off https://github.com/apple/swift-experimental-string-processing/pull/481 so they can be independently cherry-picked to 5.7:

- Fix a crash that occurred with `\o` if it was not followed by `{`.
- Allow `(?)`, which is permitted by PCRE (but is a no-op).

Resolves #472

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

File: Tests/RegexTests/LexTests.swift [hunk 1]
```diff
@@ -14,91 +14,7 @@
...
-      try src.expect("b")
-    }
-
-    diagnose("", expecting: .unexpectedEndOfInput) { src in
-      try src.expectNonEmpty()
-    }
-    diagnose("a", expecting: .unexpectedEndOfInput) { src in
-      try src.expect("a") // Ok
-      try src.expectNonEmpty() // Error
-    }
```
Comment (milseman) [inline Tests/RegexTests/LexTests.swift:57]: Why are we removing these tests?

Comment (hamishknight) [reply Tests/RegexTests/LexTests.swift]: Put them back, except the scalar tests which I moved to ParseTests

**Comment by hamishknight** [comment]
@swift-ci please test

**Review by milseman — APPROVED** [review]
LGTM
