### PR TITLE
Fix trivia in custom character classes

### LINKED ISSUE #275: Whitespace in CCCs in extended syntax causes trap when matching
The following traps in `Processor.cycle()`, due to the unescaped space inside the custom character class:

```swift
try! Regex(compiling: #"(?xx)[ \t]+"#).matchWhole(" \t ")
```

Removing the space (`[\t]`) or escaping it (`[\ \t]`) resolves the crash.

### PR DESCRIPTION
**Pull request by hamishknight**
Fix trivia matching logic in custom character classes, rather than matching and not advancing the input, we should always return `nil` to never match against the trivia. Resolves #275.

Additionally, fix custom character class parsing logic such that trivia is suitably ignored for set operations and the case where the first semantic member is `]`.

### CODE REVIEW

**Comment by hamishknight** [comment]
@swift-ci please test

File: Tests/RegexTests/MatchTests.swift [hunk 1]
```diff
@@ -1208,6 +1208,19 @@ extension RegexTests {
...
+    firstMatchTest(#" \t "#, input: " \t ", match: " \t ")
+    firstMatchTest(#"(?xx) \t "#, input: " \t ", match: "\t")
+
+    firstMatchTest(#"[ \t]+"#, input: " \t ", match: " \t ")
+    firstMatchTest(#"(?xx)[ \t]+"#, input: " \t ", match: "\t")
+    firstMatchTest(#"(?xx)[ \t]+"#, input: " \t\t ", match: "\t\t")
+    firstMatchTest(#"(?xx)[ \t]+"#, input: " \t \t", match: "\t")
+
+    firstMatchTest("(?xx)[ a && ab ]+", input: " aaba ", match: "aa")
+    firstMatchTest("(?xx)[ ] a ]+", input: " a]]a ] ", match: "a]]a")
```
Comment (natecook1000) [inline Tests/RegexTests/MatchTests.swift:1222]: 👍🏻

**Review by natecook1000 — APPROVED** [review]
LGTM!
